export const ROUTES = {
  home: '/',
  forSchool: '/for-school',
  forParent: '/for-parent',
  forSpecialist: '/for-specialist',
  pricing: '/pricing',
  resources: '/resources',
  about: '/about',
  login: '/login',
  register: '/register',
  registerRole: '/register/:role',
  forgotPassword: '/forgot-password',
  dashboard: '/dashboard',
  notFound: '*',
};
