import { motion } from 'motion/react';
import { BookIcon, SearchIcon, UsersIcon } from '@shared/components/icons';

const roles = [
  {
    Icon: SearchIcon,
    title: 'Review AI strategies for safety',
    description: 'Assess automated recommendations generated by our AI engine to ensure they are evidence-based, safe, and tailored to specific neuro-types.',
  },
  {
    Icon: BookIcon,
    title: 'Contribute to the Evidence Library',
    description: 'Submit white papers, clinical guides, and validated strategies to our central database, reaching thousands of educators and parents instantly.',
  },
  {
    Icon: UsersIcon,
    title: 'Direct collaboration with families',
    description: 'Provide micro-consultations or detailed feedback to parents and school teams through our secure, integrated messaging and case system.',
  },
];

const SpecialistRoleSection = () => (
  <section className="bg-surface px-4 pb-16 sm:px-6 lg:px-20 lg:pb-20">
    <div className="mx-auto flex max-w-[1280px] flex-col gap-10">
      <header className="flex flex-col items-center gap-3">
        <h2 className="text-center text-2xl font-bold tracking-tight text-content sm:text-3xl lg:text-[2rem]">Your role on the platform</h2>
        <span aria-hidden className="h-1 w-16 rounded-full bg-orange-400" />
      </header>

      <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {roles.map(({ Icon, title, description }, index) => (
          <motion.article
            key={title}
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-80px' }}
            transition={{ duration: 0.4, delay: index * 0.08, ease: [0.16, 1, 0.3, 1] }}
            className="flex flex-col items-center gap-4 rounded-2xl border border-border-subtle bg-surface p-6 text-center shadow-soft"
          >
            <span className="flex size-12 items-center justify-center rounded-xl bg-cta text-white">
              <Icon className="size-6" />
            </span>
            <h3 className="text-base font-bold tracking-tight text-content">{title}</h3>
            <p className="text-sm leading-relaxed text-content-muted">{description}</p>
          </motion.article>
        ))}
      </div>
    </div>
  </section>
);

export default SpecialistRoleSection;
